### PR TITLE
Corrects problem with relative requires

### LINKED ISSUE #2: Requires are relative, causing conflicts
The requires in your code are relative, so including your files from another directory causes them to fail (either not found, or conflicts with a file of the same name). This can be fixed by changing your requires to use the `__DIR__` magic constant to produce absolute paths.

### PR DESCRIPTION
**Pull request by BrandonDusseau**
Fixes #2

### CODE REVIEW

File: client.php [hunk 1]
```diff
@@ -33,9 +33,9 @@ function authenticate(){
         );
         $result = curl_post($url, $fields, array(CURLOPT_HEADER => 1));
         $res = http_parse($result);
-
```
Comment (BrandonDusseau) [inline client.php]: My editor automatically removes trailing whitespace. It doesn't hurt to leave it removed, though.

**Comment by wrenoud** [comment]
Thanks!
